### ISSUE TITLE
Reproducing code: A matter of time

### ISSUE THREAD

**Issue by liangxinyu0514** [NUSTM/CPNC#2]
Hello, I have reproduced the CPNC-I part of your code, and so far, I have completed 929 epochs, and training is still ongoing. However, in the article, it was mentioned to set the epoch to 100. I would like to know if you have encountered this issue before, and approximately how many epochs are required?

**Comment by Wusiwei0410** [comment]
Sorry, the CPNC-I model is based on the InductivE model, which needs to reach convergence about 2000 epochs (I don’t remember exactly, maybe a few thousand rounds). Because it has many operations using CPU, rather than GPU, so it takes 4-5 days to reach convergence on Conceptnet100k, and more than 7 days on ATOMIC.
The 100 epochs refer to CPNC-S model.
If you cannot use computation resources more than 7 days, I advise you to compare your designed model and CPNC-I model under the same training time setting (maybe 7 days for ATOMIC, not to be too short as possible).

I know this is a very annoying thing, and I hope my suggestion could help you.

**Comment by liangxinyu0514** [comment]
Thank you very much. Your advice helped me a lot！

**Comment by Wusiwei0410** [comment]
Well, if it is okay, I would close this issue.

**Comment by liangxinyu0514** [comment]
Very ok!



---- Replied Message ----
| From | Siwei ***@***.***> |
| Date | 09/17/2023 19:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [NUSTM/CPNC] Reproducing code: A matter of time (Issue #2) |

Well, if it is okay, I would close this issue.
